name: Build OpenWRT Firmware (19.07.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      # Adjust this once you know the exact profile from "List available profiles"
      PROFILE: tl-wr841n-v13
      PACKAGES: wpad-basic curl bash coreutils -luci -ppp -ip6tables -odhcpd-ipv6only -opkg -uhttpd -firewall

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git wget unzip python3

      - name: Download Image Builder 19.07.10
        run: |
          wget https://downloads.openwrt.org/releases/19.07.10/targets/ramips/mt76x8/openwrt-imagebuilder-19.07.10-ramips-mt76x8.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-19.07.10-ramips-mt76x8.Linux-x86_64.tar.xz
          mv openwrt-imagebuilder-19.07.10-ramips-mt76x8.Linux-x86_64 imagebuilder

      - name: List available profiles
        run: |
          cd imagebuilder
          make info | grep -i wr84 ||
