name: Native OpenWRT Build (TL-WR840N v6.2)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget curl libbz2-dev libreadline-dev libsqlite3-dev zlib1g-dev

    - name: Install Python 2.7 via pyenv
      run: |
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(~/.pyenv/bin/pyenv init -)"
        pyenv install 2.7.18
        pyenv global 2.7.18
        sudo ln -sf ~/.pyenv/versions/2.7.18/bin/python /usr/bin/python

    - name: Clone OpenWRT source
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v19.07.10

    - name: Prepare feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure build
      working-directory: openwrt
      run: |
        echo -e "CONFIG_TARGET_ramips=y\nCONFIG_TARGET_ramips_mt76x8=y\nCONFIG_TARGET_ramips_mt76x8_DEVICE_tl-wr840n-v6=y" > .config
        make defconfig

    - name: Add custom files (optional)
      working-directory: openwrt
      run: |
        if [ -d ../files ]; then cp -r ../files ./files; fi

    - name: Build firmware
      working-directory: openwrt
      run: make -j$(nproc)

    - name: Upload sysupgrade image
      uses: actions/upload-artifact@v4
      with:
        name: sysupgrade-image
        path: openwrt/bin/targets/ramips/mt76x8/*-sysupgrade.bin
