name: Build OpenWRT Firmware (19.07.10)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download ImageBuilder
      run: |
        wget https://downloads.openwrt.org/releases/19.07.10/targets/ar71xx/generic/openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64.tar.xz

    - name: Build sysupgrade image for TL-WR840N v6.2
      working-directory: openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64
      run: |
        make image PROFILE=tl-wr840n-v6 \
          PACKAGES="uhttpd php7 php7-cgi php7-mod-session php7-mod-mysqli php7-mod-json php7-mod-curl \
                    iptables ipset dnsmasq-full wpad-basic kmod-nf-nat kmod-ipt-nat kmod-ipt-conntrack \
                    coreutils busybox dropbear" \
          FILES=files/

    - name: Upload sysupgrade image
      uses: actions/upload-artifact@v4
      with:
        name: sysupgrade-image
        path: openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/*-sysupgrade.bin
