name: Native OpenWRT Build (TL-WR840N v6.2)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget python3

    - name: Clone OpenWRT source
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v19.07.10

    - name: Prepare feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure build
      working-directory: openwrt
      run: |
        echo -e "CONFIG_TARGET_ramips=y\nCONFIG_TARGET_ramips_mt76x8=y\nCONFIG_TARGET_ramips_mt76x8_DEVICE_tl-wr840n-v6=y" > .config
        make defconfig

    - name: Build firmware
      working-directory: openwrt
      run: make -j$(nproc)

    - name: Upload sysupgrade image
      uses: actions/upload-artifact@v4
      with:
        name: sysupgrade-image
        path: openwrt/bin/targets/ramips/mt76x8/*-sysupgrade.bin
