name: Build OpenWRT Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROFILE: tplink_tl-wr840n-v6
      PACKAGES: wpad-basic-mbedtls curl bash coreutils -luci -ppp -ip6tables -odhcpd-ipv6only -opkg -uhttpd -firewall4

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git wget unzip python3

    - name: Download Image Builder
      run: |
        wget https://downloads.openwrt.org/releases/22.03.5/targets/ramips/mt76x8/openwrt-imagebuilder-22.03.5-ramips-mt76x8.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-22.03.5-ramips-mt76x8.Linux-x86_64.tar.xz
        mv openwrt-imagebuilder-22.03.5-ramips-mt76x8.Linux-x86_64 imagebuilder

    - name: Confirm profile exists
      run: |
        cd imagebuilder
        make info | grep $PROFILE

    - name: Build firmware
      run: |
        cd imagebuilder
        make image PROFILE=$PROFILE PACKAGES="$PACKAGES"

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: imagebuilder/bin/targets/ramips/mt76x8/*.bin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0
        name: Trimmed OpenWRT TL-WR840N v6.2
        files: imagebuilder/bin/targets/ramips/mt76x8/*.bin        cd imagebuilder
        make image PROFILE=$PROFILE PACKAGES="$PACKAGES"

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: imagebuilder/bin/targets/ramips/mt76x8/*.bin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0
        name: Trimmed OpenWRT TL-WR840N v6.2
        files: imagebuilder/bin/targets/ramips/mt76x8/*.bin        cd imagebuilder
        make image PROFILE=$PROFILE PACKAGES="$PACKAGES"

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: imagebuilder/bin/targets/ramips/mt76x8/*.bin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0
        name: Trimmed OpenWRT TL-WR840N v6.2
        files: imagebuilder/bin/targets/ramips/mt76x8/*.bin
